spring.data.mongodb.uri=mongodb+srv://MONGODB_USERNAME:MONGODB_PASSWORD@CLUSTER_DOMAIN/DB_NAME?retryWrites=true&w=majority
logging.level.root=INFO
jwt.secret=YSasdasrJuXMIasdsadHVvQrRnbsSgaassaddsa4oFU0asdHyvhsadwe4ad3Bp21378ywashjkdasjkdasasdasd
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.mongodb.auto-index-creation=true

